### ISSUE TITLE
Unexpected stream identifier

### ISSUE THREAD

**Issue by ostinelli** [igrigorik/http-2#92] opened 2017-01-03 17:47 UTC
Hello @igrigorik,
Since upgrading from `0.8.2` to `0.8.3` nearly all of my tests in [NetHttp2](https://github.com/ostinelli/net-http2) fail (without changes to code). I'm basically implementing what is shown in examples so I'd welcome a few pointers to see what I may be doing wrong.

All of my tests fail because a `HTTP2::Error::ProtocolError` error is raised [here](https://github.com/igrigorik/http-2/blob/v0.8.3/lib/http/2/connection.rb#L333) on my [dummy_server.rb](https://github.com/ostinelli/net-http2/blob/0.14.0/spec/support/dummy_server.rb#L102) when receiving a `window_update` frame such as  `{:length=>4, :type=>:window_update, :flags=>[], :stream=>1, :increment=>13}`.

it looks like the server doesn't know how to handle `window_update` frames anymore... Is this possible or am I mistaken?

**Comment by igrigorik** [comment] 2017-01-05 05:27
It's definitely possible.. 🤕 

Reviewing the commits that went out with 0.8.2, the only one that stands out is the last (https://github.com/igrigorik/http-2/commit/128b52944a818c0a324fee395ee6b6e075e58ca5) change that started purging stale streams, but that should still have a 15s grace period.. Hmm!

Could you try locking the gem to parent of above commit and see if you get same error?

**Comment by ostinelli** [comment] 2017-01-05 10:19
I confirm that dd922c51af3c871c42702c6fb95bbeead5ac348f works perfectly. I'd need to dig deeper into the logic of `@streams_recently_closed` to provide additional feedback though.

**Comment by ostinelli** [comment] 2017-01-05 10:44
I may have found where the culprit is. Please see https://github.com/ostinelli/http-2/commit/2ca434be6dcb5afeff60617a5fcf32194d7dc35a for a patch that still passes all of Http/2 and NetHttp2 tests.

However, I didn't write a test for this specific addition as I honestly don't have enough comprehension of all of the Http2 suite. :)

**Comment by igrigorik** [comment] 2017-01-06 06:24
Thanks for digging into it, very helpful!

http://httpwg.org/specs/rfc7540.html#WINDOW_UPDATE

> WINDOW_UPDATE can be sent by a peer that has sent a frame bearing the END_STREAM flag. This means that a receiver could receive a WINDOW_UPDATE frame on a "half-closed (remote)" or "closed" stream. A receiver MUST NOT treat this as an error (see Section 5.1).

Can you try this patch.. 

```diff
diff --git a/lib/http/2/connection.rb b/lib/http/2/connection.rb
index 1553ef1..44cac8f 100644
--- a/lib/http/2/connection.rb
+++ b/lib/http/2/connection.rb
@@ -313,11 +313,12 @@ module HTTP2
             if (stream = @streams[frame[:stream]])
               stream << frame
             else
+              case frame[:type]
               # The PRIORITY frame can be sent for a stream in the "idle" or
               # "closed" state. This allows for the reprioritization of a
               # group of dependent streams by altering the priority of an
               # unused or closed parent stream.
-              if frame[:type] == :priority
+              when :priority
                 stream = activate_stream(
                   id:         frame[:stream],
                   weight:     frame[:weight] || DEFAULT_WEIGHT,
@@ -327,6 +328,14 @@ module HTTP2
 
                 emit(:stream, stream)
                 stream << frame
+
+              # WINDOW_UPDATE can be sent by a peer that has sent a frame
+              # bearing the END_STREAM flag. This means that a receiver could
+              # receive a WINDOW_UPDATE frame on a "half-closed (remote)" or
+              # "closed" stream. A receiver MUST NOT treat this as an error
+              # (see Section 5.1).
+              when :window_update
+                process_window_update(frame)
               else
                 # An endpoint that receives an unexpected stream identifier
                 # MUST respond with a connection error of type PROTOCOL_ERROR.
@@ -415,8 +424,7 @@ module HTTP2
         when :settings
           connection_settings(frame)
         when :window_update
-          @remote_window += frame[:increment]
-          send_data(nil, true)
+          process_window_update(frame)
         when :ping
           if frame[:flags].include? :ack
             emit(:ack, frame[:payload])
```

**Comment by ostinelli** [comment] 2017-01-06 11:06
This solves some issues but not all of them. To be more precise, the sending of bodies > 65,535 results in hangs, so I guess the `window_update` frame does not get properly processed and the client awaits for a server answer.

**Comment by ostinelli** [comment] 2017-01-16 11:12
Hello @igrigorik, anything I can do to help proceed? Currently the example implementations seem to be broken.

**Comment by igrigorik** [comment] 2017-01-17 00:20
@ostinelli apologies, this one slipped through the cracks. Will try to get to it in the next few days.

**Comment by kenichi** [comment] 2017-01-22 00:24
hello @ostinelli, nice to meet you. i came across your [client](/ostinelli/net-http2) while extracting my [own](/kenichi/h2) from [reel](/kenichi/reel/tree/h2) tests. very nice work; many similarities, but still enough differences to warrant separate projects i think. i also have run into this issue with 0.8.3.

hi again, @igrigorik. digging a bit further, i have had some success with the following diff (on top of above patch). the issue seems to arise when a http-2 based server is handling window updates on a stream that has been closed even though the `@send_buffer` is not empty. note the addition to `Stream#end_stream?`. the stream could have been closed by the state management in `Stream#send` prior to actual completion.

```diff
diff --git a/lib/http/2/flow_buffer.rb b/lib/http/2/flow_buffer.rb
index aecb5f1..db0f744 100644
--- a/lib/http/2/flow_buffer.rb
+++ b/lib/http/2/flow_buffer.rb
@@ -22,7 +22,8 @@ module HTTP2
     #
     # @param frame [Hash]
     # @param encode [Boolean] set to true by co
-    def send_data(frame = nil, encode = false)
+    # @param window_update [Boolean] true if called during window_update processing
+    def send_data(frame = nil, encode = false, window_update = false)
       @send_buffer.push frame unless frame.nil?

       # FIXME: Frames with zero length with the END_STREAM flag set (that
@@ -46,14 +47,20 @@ module HTTP2
           # if no longer last frame in sequence...
           frame[:flags] -= [:end_stream] if frame[:flags].include? :end_stream

-          @send_buffer.unshift chunk
+          @send_buffer.unshift chunk if chunk[:length] != 0 || chunk[:flags].include?(:end_stream)
           sent = @remote_window
         else
           sent = frame_size
         end

         frames = encode ? encode(frame) : [frame]
-        frames.each { |f| emit(:frame, f) }
+        frames.each do |f|
+          emit(:frame, f)
+          if window_update && @state == :half_closed_remote && end_stream?(f)
+            event(:local_closed)
+            complete_transition(f)
+          end
+        end
         @remote_window -= sent
       end
     end
@@ -61,7 +68,7 @@ module HTTP2
     def process_window_update(frame)
       return if frame[:ignore]
       @remote_window += frame[:increment]
-      send_data
+      send_data nil, false, true
     end
   end
 end
diff --git a/lib/http/2/stream.rb b/lib/http/2/stream.rb
index 3015c5e..135e4f4 100644
--- a/lib/http/2/stream.rb
+++ b/lib/http/2/stream.rb
@@ -591,7 +591,7 @@ module HTTP2
     def end_stream?(frame)
       case frame[:type]
       when :data, :headers, :continuation
-        frame[:flags].include?(:end_stream)
+        @send_buffer.empty? && frame[:flags].include?(:end_stream)
       else false
       end
     end
```

not intended as final by any means, but i am interested to know if this works for either of you.  i have been testing serving both a 6mb and 18mb jpg, as a direct response and a push promise, with @ostinelli's client, my own, nghttp, safari tech preview, and chrome canary.

**Comment by igrigorik** [comment] 2017-01-22 22:11
> @send_buffer.unshift chunk if chunk[:length] != 0 || chunk[:flags].include?(:end_stream)

When would :length ever be 0? Also, we explicitly remove :end_stream in the line above. I'm not sure I follow what these checks are doing.

> frames.each do |f| ...

This seems to imply that we can emit multiple :local_closed events, which also doesn't feel right.

---

Stepping back.. I think we should start with writing down a test to flex this code path. That way, we can be sure it works, and won't get broken in the future. @ostinelli @kenichi any chance you could take a run at that? My laptop just died on me (sigh), and I'm on the road, it'll take me at least a few days to fix it and rebuild my environment.

**Comment by kenichi** [comment] 2017-01-23 18:24
i'm happy to give it a shot, but i need to make sure i understand the complete issue first. sorry, i should start with what i saw happening, and describe the reasoning behind the above hacks:

as of 0.8.3, an http-2 based client sends 2 window update frames when receiving a stream body that is large, one on stream 0 (connection) and one on the stream in question. the first patch makes the `HTTP::Server` instance call its `process_window_update`; eventually, this emits a 0-length, empty body, non-end-stream-flagged, frame due to the logic in the while loop. the listener attached to the `:frame` event is only the actual server (reel in this case) and it is expecting *bytes*. this is the first stacktrace i got, since i have logging in the `:frame` handler, like the example. http-2 gem was calling the listener with a plain `Hash` instead. this is why i added the condition on the `@send_buffer.unshift`.

additionally, since `process_window_update` is coming in sort of "out of band", all the state management in `Stream#send` is being bypassed, since it calls directly into `FlowBuffer#send_data`. this is why i added the extra state handling the frames iteration block, since that is when a stream could *actually* close. example: server calls `Stream#data` after properly calling `headers`, with a blob that is large > 6mb. http-2 emits binary frames to send until it hits 0 of the window. method returns. data is now buffered in that `Stream`'s `@send_buffer` until a client sends a window update. after the method returns, everything is async. this is why i added the `@send_buffer.empty?` check to `Stream#end_stream?`.

> `@send_buffer.unshift chunk if chunk[:length] != 0 || chunk[:flags].include?(:end_stream)`
>
> When would :length ever be 0? Also, we explicitly remove :end_stream in the line above. I'm not sure I follow what these checks are doing.

see the 2nd paragraph for when it would be 0, though i haven't completely tracked down the exact cause. i believe the removal of the end_stream flag from the frame is legit, when chunking up by window size, however; i think there could be a bug where it never is added back to the final frame. also, note that the flag is removed from the `frame`, not the `chunk` sliced out of it.

> `frames.each do |f| ...`
>
> This seems to imply that we can emit multiple :local_closed events, which also doesn't feel right.

I left this code without a check for that, as if other code misbehaves, that is completely possible. the checks for end_stream flag and so on should prevent that from happening, but i'm open to gating it here as well.

**Comment by igrigorik** [comment] 2017-01-29 07:01
@kenichi thanks for the deep dive. Still trying to grok the edge cases here, as it feels like we're patching up/over some larger underlying issues here.

**Comment by kenichi** [comment] 2017-01-31 00:04
@igrigorik 👍  i agree, and i'll also be looking to see if i can come up with solid tests for all of this.

**Comment by ostinelli** [comment] 2017-02-28 11:33
FYI, due to these issues (the `unexpected stream identifier` error and impossibility to send/receive requests with bodies > 65,535 bytes) I've had to [lock the version used by NetHttp2 to `0.8.2`](https://github.com/ostinelli/net-http2/blob/0.15.0/net-http2.gemspec#L22).

However, `0.8.2` had a memory leak that was reported in the following issues:

  * https://github.com/igrigorik/http-2/issues/73
  * https://github.com/ostinelli/net-http2/issues/7

Hence I'm currently monkey-patching it (see [here](https://github.com/ostinelli/net-http2/blob/0.15.0/lib/http2_patch.rb)), and everything works as expected. Obviously this is only a temporary solution waiting for a fix to `0.8.3`.

I'm not sure how this is progressing and if / how I could help, hence I'm providing you here with how I'm currently dealing with this.

**Comment by kenichi** [comment] 2017-02-28 18:12
hello all - first, i apologize for the delay. i have been trying to distill the problems down to unit tests and have mostly failed, but i have at least one test that demonstrates the problem i've been seeing.

https://github.com/igrigorik/http-2/compare/master...kenichi:window_update_test

i used threads and pipes to simulate real world asynchronicity, and this demonstrates how the call to `Stream#data` can return before all the data is sent. that is not a bug, but the state it leaves behind is. once the window is exceeded, before receipt of window_update from client:

* `Stream#data` may have queued frames in the `@send_buffer` via:
    1. `Stream#send` (consider a different name that doesn't override `Object#send`?)
    2. `Stream/FlowBuffer#send_data`
* `Stream#send` receives the final data frame, which has `:end_stream` flag
    1. calls `Stream#transition` setting `@state` to `:closing` https://github.com/igrigorik/http-2/blob/master/lib/http/2/stream.rb#L460
    3. `@remote_window` is 0, so the frame is pushed onto `@send_buffer` and left there
    4. `Stream/FlowBuffer#send_data` returns, and `Stream#complete_transition` is called
    5. `:closed` event is emitted and the code @ostinelli was seeing deletes the stream instance.

now, when the server finally does receive window_update for that stream... hopefully you see where this is going.

@ostinelli's patch for holding on to closed streams a bit longer does make things work up to a point. my weird hacks for state put a band aid over a (at the time) misunderstood problem. your patch missed that `process_window_update` should have been called on the stream in the second hunk, and that calling `process_window_update` in the third hunk causes, in this case, `Connection/FlowBuffer#send_data` to *not* encode the frame (which is why i was seeing a raw frame hash instead of a `HTTP2::Buffer` in my `:frame` handler).

so backing way up: do we want streams to enter a `:closed` state and run the `:close` callback while frames are still in the `@send_buffer`? the whole complicated state management around a stream's lifecycle needs a bit of revisiting from this angle.

**Comment by kenichi** [comment] 2017-03-05 19:57
writing that out helped me solidify my thoughts into a couple [tests](https://github.com/igrigorik/http-2/compare/master...kenichi:stream_close_test).

**Comment by igrigorik** [comment] 2017-03-08 12:53
Should be resolved via #95 -- thanks @kenichi!

@ostinelli closing this, please reopen if necessary.

**Closed by igrigorik** 2017-03-08 12:53 UTC

**Comment by ostinelli** [comment] 2017-03-30 09:42
@igrigorik and @kenichi unfortunately #95 does not solve it. Reopening here since I cannot reopen #95.

**Comment by ostinelli** [comment] 2017-03-30 09:43
@igrigorik and @kenichi unfortunately #95 does not solve it. Can't reopen here, nor #95.
