### ISSUE TITLE
HTTP2::Error::ProtocolError

### ISSUE THREAD

**Issue by maclover7** [igrigorik/http-2#45] opened 2016-01-09 05:05 UTC
Hi,

First, let me start off by saying thank you for working on this awesome gem! By having it be written in pure Ruby, this means C extension issues are out of the question :pray: :clap: 

Unfortunately, I have run into a bit of a speed bump with http-2. I am trying to add support for it (via https://github.com/mironrb/miron/pull/28) to Miron, a gem I am working on as a kind of Rack 2.0. I am trying to get the server running, but when I try to load up the page with the server running from Chrome on my Mac, I encounter a `HTTP2::Error::ProtocolError`.

To reproduce:
- Clone down branch from PR
- bundle, etc.
- `cd examples`
- `../exe/miron server --mironfile=app.rb --handler=http2 --port=8080`

Let me know if I can provide anything else to try and debug this, and find the source of the error.

**Comment by igrigorik** [comment] 2016-01-12 00:13
Hmm, I think the issue is that you don't have `Logger` class defined in your handler. We call the :stream callback and that blows up, causing the protocol error. Try adding this to your handler:

```ruby
      class Logger
        def initialize(id)
          @id = id
        end

        def info(msg)
          puts "[Stream #{@id}]: #{msg}"
        end
      end
```

We should figure out how to provide better error stacks here.

**Comment by maclover7** [comment] 2016-01-12 02:31
Ok - was able to get working by adding this. Would you be able to change the internals to allow the stacktrace to appear naturally in the terminal -- currently, if there's an error, all you get is an Error with no stacktrace, which makes debugging super hard. Also, was able to get my example working locally. You can check out my PR [here](https://github.com/mironrb/miron/pull/28) to add http-2 to Miron.

Any suggestions about how to properly test the HTTP2 handler? You can check out the other handlers as examples.

**Comment by igrigorik** [comment] 2016-01-13 21:11
Nice, glad it's working!

- stacktraces: yes, I'll look into that. It's bitten me a few times now.
- testing: one idea would be subscribe to [frame events](https://github.com/igrigorik/http-2/blob/master/spec/connection_spec.rb#L334), decode those, and check that the data in those is as you expect? See connection_spec.rb for examples.

**Comment by maclover7** [comment] 2016-01-13 22:25
Seems like an interesting way to do things, but not sure if it's best to go that route. All of the other existing handlers (Puma, Thin, etc.) all use the same testing pattern to ensure consistency across how handlers handle HTTP requests. Not sure it would be good if http-2 deviated away from that. Any ideas about how to wire this up? Just requires creating a server in a background thread, and then a simple client to make a request, and return back the data.

I already have a [server](https://github.com/mironrb/miron/blob/http2/spec/support/servers.rb#L14-L24) and a [client](https://github.com/mironrb/miron/blob/http2/spec/support/http2.rb) built, but would appreciate some additional guidance.

**Comment by igrigorik** [comment] 2016-01-14 01:31
Well, it looks like you rely on httparty, so sounds like that gem would need to add an http-2 backend? Not sure what's involved there though.. The important bit here is to make sure it's wired up correctly: one connection per origin that's shared betweeen all muxed requests. /cc @jnunemaker

**Comment by maclover7** [comment] 2016-01-14 01:36
I already have a [server](https://github.com/mironrb/miron/blob/http2/spec/support/servers.rb#L14-L24) and a [client](https://github.com/mironrb/miron/blob/http2/spec/support/http2.rb) built, and have the [test](https://github.com/mironrb/miron/blob/http2/spec/handlers/http2_spec.rb) ready to go as well, but would appreciate help with how to get data back to the tests from the `HTTP2::Client`.

**Comment by igrigorik** [comment] 2016-01-14 05:08
Oh. Have you looked at https://github.com/igrigorik/http-2/blob/master/example/client.rb#L78-L84? I think that's all you need.

**Comment by maclover7** [comment] 2016-01-15 03:04
Added, but still not working. Would you be able to clone down locally and work on this? As soon as HTTP/2 server is started everything hangs up forever, despite that it's running in a separate thread (?).
<img width="445" alt="screen shot 2016-01-14 at 10 03 05 pm" src="https://cloud.githubusercontent.com/assets/3020626/12344411/ae134ccc-bb0a-11e5-99a7-367ae2182603.png">

Getting tests running is the only thing stopping this from getting merged :)

**Comment by jnunemaker** [comment] 2016-01-15 21:18
FWIW, HTTParty doesn't support multiple backends so net/http it is for now.

**Comment by alloy** [comment] 2016-01-16 12:37
> all you get is an Error with no stacktrace, which makes debugging super hard. 

FYI Ruby should be storing the original exception in [`Exception#cause`](http://ruby-doc.org/core-2.3.0/Exception.html#method-i-cause).

**Comment by igrigorik** [comment] 2016-01-29 05:20
https://github.com/igrigorik/http-2/commit/d62b80ad5ea248380581f76b968a74c74fb49193 should fix the problem with swallowed exceptions. Closing this bug. 

@maclover7 let's continue the testing discussion on the mironrb repo.

**Closed by igrigorik** 2016-01-29 05:20 UTC
